---
title: "prediction_output"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Load the required libraries
```{r}
#rm(list=ls(all=T))
library(data.table)
library(caret)
```
```{r, echo=FALSE}
load("data_prep.RData")
load("rf_random.RData")
```
## Machine learning part
load required libraries
```{r}
set.seed(123)
library(caret)
library(data.table)
library(ROCR)
library(OptimalCutpoints)

print(rf_random)
plot(rf_random)
```

Do prediction on validation set
```{r}
data_type1_tr = lapply(data_type1_tr,as.numeric)
data_type1_tr = data.frame(data_type1_tr)
data_type1_tr$outcome = as.factor(data_type1_tr$outcome)
N=dim(data_type1_tr)[1]
X = c(1:N)
samp = sample(X,15000)
data_type1_tr = data_type1_tr[samp,]
inTrain <- createDataPartition(data_type1_tr$outcome, p=0.7, list = FALSE)
tr_set = data_type1_tr[inTrain,]
te_set = data_type1_tr[-inTrain,]
pred_rf = predict(rf_random, te_set)
confmat = table(pred_rf, te_set$outcome)
sens = confmat[1,1]/(confmat[1,1]+confmat[1,2])
spec = confmat[2,2]/(confmat[2,2]+confmat[2,1])
```

plot the ROC and compute AUC
```{r}
result.pr = predict(rf_random, type="prob", newdata=te_set)[,2]
result.pred = prediction(result.pr, te_set$outcome)
result.perf = performance(result.pred,"tpr","fpr")
result.auc = performance(result.pred, "auc")
result.auc@y.values
plot(result.perf,main="ROC Curve for type 1 data predction",col=2,lwd=2)
abline(a=0,b=1,lwd=2,lty=2,col="gray")
```

now do the prediction on the test set
```{r}
data_type1_te = lapply(data_type1_te, as.numeric)
data_type1_te = data.frame(data_type1_te)
predict_te = predict(rf_random, data_type1_te)
```

now build model for the rest of the types (non-type1 data)
```{r}
data_rest_tr = lapply(data_rest_tr, as.numeric)
data_rest_tr = data.frame(data_rest_tr)
data_rest_tr$outcome = as.factor(data_rest_tr$outcome)
set.seed(234)
X = c(1:dim(data_rest_tr)[1])
samp = sample(X,15000)
data_rest_tr = data_rest_tr[samp,]
inTrain <- createDataPartition(data_rest_tr$outcome, p=0.7, list = FALSE)
tr_set = data_rest_tr[inTrain,]
te_set = data_rest_tr[-inTrain,]
control <- trainControl(method="repeatedcv", number=10, search="random")
load('rf_random2.RData')
```

do prediction on validation set
```{r}
pred_rf = predict(rf_random2, te_set)
confmat = table(pred_rf, te_set$outcome)
sens = confmat[1,1]/(confmat[1,1]+confmat[1,2])
spec = confmat[2,2]/(confmat[2,2]+confmat[2,1])

# check ROC
result.pr = predict(rf_random2, type="prob", newdata=te_set)[,2]
result.pred = prediction(result.pr, te_set$outcome)
result.perf = performance(result.pred,"tpr","fpr")
result.auc = performance(result.pred, "auc")
result.auc@y.values

plot(result.perf,main="ROC Curve for non-type1 data prediction",col=2,lwd=2)
abline(a=0,b=1,lwd=2,lty=2,col="gray")
```

now do the prediction on the test set
```{r}
data_rest_te = lapply(data_rest_te, as.numeric)
data_rest_te = data.frame(data_rest_te)
predict_te = predict(rf_random2, data_rest_te)
```